// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMC_OdJcW-tMrwOu5yadpkkk1Rx0vlU_o',
    appId: '1:336547930974:web:18cab3873d46759760a5cf',
    messagingSenderId: '336547930974',
    projectId: 'finance-app-d0d00',
    authDomain: 'finance-app-d0d00.firebaseapp.com',
    databaseURL: 'https://finance-app-d0d00-default-rtdb.firebaseio.com',
    storageBucket: 'finance-app-d0d00.firebasestorage.app',
    measurementId: 'G-JD2BCTFP4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRcog-M75I4p7oP_OVCIqwH0saUKb8GU8',
    appId: '1:336547930974:android:6a5e4b30495b2b6560a5cf',
    messagingSenderId: '336547930974',
    projectId: 'finance-app-d0d00',
    databaseURL: 'https://finance-app-d0d00-default-rtdb.firebaseio.com',
    storageBucket: 'finance-app-d0d00.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMC_OdJcW-tMrwOu5yadpkkk1Rx0vlU_o',
    appId: '1:336547930974:web:89dc2e14de5f7a1760a5cf',
    messagingSenderId: '336547930974',
    projectId: 'finance-app-d0d00',
    authDomain: 'finance-app-d0d00.firebaseapp.com',
    databaseURL: 'https://finance-app-d0d00-default-rtdb.firebaseio.com',
    storageBucket: 'finance-app-d0d00.firebasestorage.app',
    measurementId: 'G-DZKDVJJPL4',
  );
}
